name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup NDK
        uses: nttld/setup-ndk@v1.5
        with:
          ndk-version: r26c

      - name: Build Dobby
        run: |
          git clone https://github.com/jmpews/Dobby.git
          cd Dobby
          mkdir build && cd build
          cmake .. \
                -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-24 \
                -DCMAKE_BUILD_TYPE=Release
          make -j4
          cp libdobby.a ../../overlay/libs/Dobby/

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-24 \
                ..
          make
          
      - name: Create Zip
        run: |
          mkdir -p output/zygisk/arm64-v8a
          cp build/*.so output/zygisk/arm64-v8a/
          cp module.prop output/
          cd output && zip -r ../rov-esp-mod.zip .
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rov-esp-mod
          path: rov-esp-mod.zip
